# netlify.toml
[build]
  command = "pip install mkdocs mkdocs-material && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.9"  # Ensure this is set to a version that meets your requirements
