# netlify.toml
[build]
  command = "export PATH=$PATH:/opt/buildhome/.local/share/mise/installs/python/3.9.20/bin && pip install mkdocs mkdocs-material && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.9"  # Ensure this is set to a version that meets your requirements
