name: Auto Merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is from the user and has no conflicts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            const isUser = pr.user.login === 'mclearc'; // Replace with your GitHub username
            
            if (isUser && pr.state === 'open') {
              const { data: mergeableState } = await github.pulls.get({
                owner,
                repo,
                pull_number: pr.number,
              });

              if (mergeableState.mergeable === true) {
                await github.pulls.merge({
                  owner,
                  repo,
                  pull_number: pr.number,
                });
                console.log(`Merged PR #${pr.number}`);
              } else {
                console.log(`PR #${pr.number} is not mergeable.`);
              }
            } else {
              console.log(`PR #${pr.number} is not from the user or not open.`);
            }
