name: Auto Merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is from the user and has no conflicts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            const isUser = pr.user.login === 'mclearc';
            
            if (isUser && pr.state === 'open') {
              // Wait for mergeable status to be computed
              await new Promise(resolve => setTimeout(resolve, 5000));
              
              const pullRequest = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: pr.number,
              });

              if (pullRequest.data.mergeable === null) {
                console.log('Mergeable status is still being computed');
                return;
              }

              if (pullRequest.data.mergeable === true) {
                await github.rest.pulls.merge({
                  owner,
                  repo,
                  pull_number: pr.number,
                });
                console.log(`Merged PR #${pr.number}`);
              } else {
                console.log(`PR #${pr.number} is not mergeable.`);
              }
            } else {
              console.log(`PR #${pr.number} is not from the user or not open.`);
            }
